version: '3'
services:
  jow_web:
    container_name: frauke_web
    build: ./
    hostname: web
    ports:
      - "8004:8004"
    volumes:
      - /home/ubuntu/frauke_stegmann_website/app/static/db/db.json:/app/static/db/db.json
      - /home/ubuntu/frauke_stegmann_website/app/static/images/:/app/static/images/
      - /home/ubuntu/frauke_stegmann_website/app/static/pdf/:/app/static/pdf/
    env_file:
      - "envfile"
networks:
  default:
    external:
      name: websites
